### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by xyproto** [hoisie/web#104]
Hi,

I just packaged web.go as an unofficial Arch Linux package.
However, I'm having difficulties finding the version number for web.go. Is it 1.0? 0.1? 3.141592653589793? :)

Could you please include a version number in the readme file?
The version number for the branch/tag of web.go that is selected at install time by "go get" would be great.

Thank you.

**Comment by hoisie** [comment]
I believe subsequent versions of Go are going to support some kind of package management system. I'll defer this until that happens :)
