### ISSUE TITLE
Is it possible to call methods from an interface?

### ISSUE THREAD

**Issue by Altonymous** [hoisie/web#130]
Here's a small example.  This doesn't compile because web.Get doesn't like me passing an interface method.

https://gist.github.com/Altonymous/c95c233b21ac7de3b7bc

I've also tried...
  var webContext *web.Context = new(web.Context)
  web.Get("/machines/?", s.index(webContext))

I'm not sure if there is a way to do this, but if there is I'd appreciate knowing how.

**Comment by xyproto** [comment]
It feels like a cludge, but if s.index returns a function that handles the request, it works.

Example: https://github.com/xyproto/siteengines/blob/73399/wikiengine.go#L147
