### ISSUE TITLE
web.RunScgi panics if the scgi client header misses a field

### ISSUE THREAD

**Issue by mpl** [hoisie/web#166]
Hey,

I've noticed while making https://github.com/mpl/scgiclient/blob/master/main.go
that if a client sent an scgi header that didn't have one of those fields:

        "CONTENT_LENGTH"
        "SCGI"
        "REQUEST_METHOD"
        "SERVER_PROTOCOL"

RunScgi would panic. Which seems a bit dangerous, as someone could write a malicious client to crash web.go, no?

I haven't investigated further but I think it was coming from
httpReq, err := cgi.RequestFromMap(headers)
so maybe it's just enough to recover from a panic around here or something.

**Comment by hoisie** [comment]
Yes, it should gracefully handle missing fields, not crash. I'll look into it.
