### ISSUE TITLE
webgo.io link is broken

### ISSUE THREAD

**Issue by rminnich** [hoisie/web#192]
The webgo.io link doesn't work.

**Comment by godolatry** [comment]
Nine days later, it's still not working, and something is a bit odd.  If I go to https://www.nic.io/go/whois/ and try to look up the domain, it hangs waiting for www.nic.io.  This implies that the problem is not that the owner simply hasn't paid his domain renewal bill.

**Comment by kirillDanshin** [comment]
@rminnich 
@godolatry
I just send @hoisie an email about transfering webgo. Hope he read it ASAP.

**Comment by kirillDanshin** [comment]
@rminnich @godolatry hi again
@hoisie wasn't reply me so [I've created a fork](https://github.com/GuavaStudio/web) and fix some bugs in it already. I'll host the website on my domain soon.

**Comment by Andrew-liu** [comment]
@kirillDanshin Can remove the API docs to github project wiki. I think It is very well.

**Comment by kirillDanshin** [comment]
@Andrew-liu ok I'll do it

**Comment by hoisie** [comment]
The links have been updated.
